services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-mongo-verba
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    volumes:
      - mongo_verba_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend-mongo-verba
    ports:
      - 3000:3000
    environment:
      DB_NAME: ${MONGO_DB_NAME}
      MONGO_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}
        - VITE_BASE_URL=${FRONTEND_BASE_URL}
    container_name: frontend-mongo-verba
    ports:
      - 2319:80


volumes:
  mongo_verba_data:

networks:
  mongo-naga-net:
