services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-mongo-verba
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-mongo-verba
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017
      ME_CONFIG_BASICAUTH: false

  backend:
    build:
      context: ./backend
    container_name: backend-mongo-verba
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: frontend-mongo-verba
    ports:
      - 2319:80

networks:
  mongo-naga-net:
