services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-mongo-verba
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    volumes:
      - mongo_verba_data:/data/db
      - ./dev/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    build:
      context: ./backend
    container_name: backend-mongo-verba
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DB_NAME: ${MONGO_DB_NAME}
      MONGO_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    depends_on:
      - mongodb
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:3000/health/liveness']
      interval: 5s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_ENVIRONMENT=development
    container_name: frontend-mongo-verba
    ports:
      - 2319:80
    depends_on:
      backend:
        condition: service_healthy

volumes:
  mongo_verba_data:

networks:
  mongo-naga-net:
