services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-mongo-verba
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mongo-verba
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./dev/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    image: node:22-alpine
    container_name: backend-mongo-verba
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DB_NAME: mongo-verba
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      ENABLE_INSERT_QUOTE: true
    depends_on:
      - mongodb
    command: npm run dev
    working_dir: /app
    volumes:
      - ./backend:/app
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://localhost:3000/health/liveness']
      interval: 5s
      timeout: 10s
      retries: 3

  frontend:
    image: node:22-alpine
    environment:
      - VITE_ENVIRONMENT=development
    container_name: frontend-mongo-verba
    ports:
      - 5173:5173
    depends_on:
      backend:
        condition: service_healthy
    command: npm run dev -- --host
    working_dir: /app
    volumes:
      - ./frontend:/app

networks:
  mongo-naga-net:
